# Workflow for triggering tests/long_performance
on:
  workflow_dispatch:
name: Short Performance XFS Test
jobs:
  short-performance-xfs:
    name: Short Performance XFS
    runs-on: self-hosted
    timeout-minutes: 4320
    steps:
      - name: Clean
        run: rm -rf ${GITHUB_WORKSPACE}/*
      - name: Checkout build scripts
        run: git clone ~/harness.git
      - name: Checkout zbdbench
        uses: actions/checkout@v2
        with:
          repository: westerndigitalcorporation/zbdbench
          ref: v0.1.1
          path: harness/rocksdb-context/zbdbench
      - name: Checkout rocksdb
        uses: actions/checkout@v2
        with:
          repository: facebook/rocksdb
          ref: v7.0.2
          path: harness/rocksdb-context/rocksdb
      - name: Checkout aquafs
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: harness/rocksdb-context/rocksdb/plugin/aquafs
      - name: Run short performance test 1TB
        run: cd harness && st --silent -o logs/make -- sudo with-xfs --disk 1TB -- make NO_VAGRANT=1 results/xfs-short.xml 
      - name: Collect Results
        run: cd harness && make NO_VAGRANT=1 upload 
        if: always()
      - name: Remove images
        run: podman rmi --force --all
        if: always()

