# Workflow for triggering tests/quick_performance
on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'
name: Short Performance Test
jobs:
  quick-performance:
    runs-on: self-hosted
    timeout-minutes: 1440
    steps:
      - name: Clean
        run: rm -rf ${GITHUB_WORKSPACE}/*
      - name: Checkout build scripts
        run: git clone ~/harness.git
      - name: Checkout zbdbench
        uses: actions/checkout@v2
        with:
          repository: westerndigitalcorporation/zbdbench
          ref: v0.1.1
          path: harness/rocksdb-context/zbdbench
      - name: Checkout rocksdb
        uses: actions/checkout@v2
        with:
          repository: facebook/rocksdb
          ref: v7.0.2
          path: harness/rocksdb-context/rocksdb
      - name: Checkout aquafs
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: harness/rocksdb-context/rocksdb/plugin/aquafs
      - name: Run short performance test
        run: cd harness && st --silent -o logs/make -- disk-select --disk 1TB -- make NO_VAGRANT=1 results/aquafs-quick.xml 
      - name: Collect Results
        run: cd harness && make NO_VAGRANT=1 upload 
        if: always()
      - name: Remove images
        run: podman rmi --force --all
        if: always()
